version: '3.0'
services:
  reflector:
    build: reflector
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      REFLECTOR_DOMAIN: demo.my-devices.net
      REFLECTOR_LICENSE: /home/reflector/etc/reflector.license
      HTTP_PORT: 8000
      POSTGRES_DATABASE: reflector
      POSTGRES_USERNAME: reflector
      POSTGRES_PASSWORD: reflector
      POSTGRES_HOST: postgres
      MIGRATE_SCHEMA: "true"
      LOGCHANNEL: file
      LOGPATH: /home/reflector/var/log/reflector.log
    volumes:
      - logvolume:/home/reflector/var/log

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: reflector
      POSTGRES_PASSWORD: reflector
      POSTGRES_DB: reflector
    volumes:
      - datavolume:/var/lib/postgresql/data
    ports:
       - "127.0.0.1:5432:5432"

  haproxy:
    build: haproxy
    depends_on:
      - reflector
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: "redis:alpine"
    restart: always

volumes:
  logvolume:
  datavolume:
