FROM macchina/reflector:latest-postgres
COPY reflector.license /home/reflector/etc/reflector.license
COPY reflector.properties /home/reflector/etc/reflector.properties
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
